readme.md

Just deleted the second instance of The Dispossessed, it was duplicated ;]

Duplicated

---

readme.md

- Added more books from the "Old Man's War" Series
- Added "Daemon" series by Daniel Suarez (not to be confused with "Daemons, Inc." by Camille Bacon-Smith, which I think might be on this list by mistake since it is definitely not in the same league as most of the rest of the books listed here)

More by John Scalzi, new books by Daniel Suarez

---

readme.md

by Greg Egan and Hannu Rajaniemi.
Both authors deal with topics such as The Singularity, post-humanism and mind uploading.
Egan's books tend to be quite technical, and would be classified as [Hard science fiction](https://en.wikipedia.org/wiki/Hard_science_fiction). But that's why I love them.
Hannu Rajaniemi's trilogy I just finished reading, it takes place in a post-human solar system. Some of it's themes are AI, virtual reality, and quantum physics.

Added a few great books

---

readme.md

Add "The End of Eternity" a great book I read a few years ago. A time travel adventure! 
I also add the books proposed by @cassidoo on this [comment] (https://github.com/sindresorhus/awesome-scifi/issues/9#issuecomment-70958833)

Add some good sci-fi books

---

readme.md

Added:
- [Blade Runner](http://www.imdb.com/title/tt0083658/)
- [2001: A Space Odyssey](http://www.imdb.com/title/tt0062622/)
- [A Clockwork Orange](http://www.imdb.com/title/tt0066921/)
- [Metropolis](http://www.imdb.com/title/tt0017136/)
- [The Matrix](http://www.imdb.com/title/tt0133093/)
- [Primer](http://www.imdb.com/title/tt0390384/)
- [La Jetée](http://www.imdb.com/title/tt0056119/)
- [Solaris](http://www.imdb.com/title/tt0307479/)
- [Brazil](http://www.imdb.com/title/tt0088846/)
- [Eraserhead](http://www.imdb.com/title/tt0074486/)
- [Minority Report](http://www.imdb.com/title/tt0181689)
- [Godzilla](http://www.imdb.com/title/tt0047034/)
- [Galaxy Quest](http://www.imdb.com/title/tt0177789/)
and
- [Dr. Who](http://www.imdb.com/title/tt0436992/)
- [Twilight …

Add more moves + TV shows

---

readme.md

I loved the novel for its epic story and the film for its characters; and I think both would be good additions to this list :cake:

Add 'Where Late the Sweet Birds Sang' and 'Gattaca'

---

readme.md

Added Continuum, a SciFi TV show I've fallen into love with recently.

Add Continuum

---

readme.md

One of my favorite science fiction TV shows of all time. Though post season 2(of 5) the story gets a bit weird for my taste, it's still pretty awesome. The first season is pretty spectacular.

Added Fringe

---

readme.md

The story unfolds over two different time periods(30s-40s and the 90s). Has some historical figures as characters, most notably Alan Turing. World War 2, Cryptography, Bletchley Park, hunt for burried Nazi treasure... whats not to love.

Add Cryptonomicon, by Neal Stephenson

---

readme.md

Two great sci-fi movies from recent years, IMO.

Added Interstellar and Inception to movies list

---

readme.md

Add Dune, The City of Lost Children and Twelve Monkeys

---

readme.md

A classic, the book Blade Runner was based on. Kinda surprised that it's not on the list already.

Add Do Androids Dream of Electric Sheep?, by Philip K. Dick

---

readme.md

Probably the first Asimov story I read. Good memories, great book.

Added 'The Gods Themselves' by Isaac Asimov

---

readme.md

Quiet an interesting book, and my first contact with Hamilton's work outside the Commonwealth universe

Adding 'Manhattan in Reverse' by Peter F. Hamilton

---

readme.md

Added descriptions for most of the sub-genres. Wasn't sure about some of the others - any help would be appreciated.

Descriptions for sub-genres

---

readme.md

I loved this book, and I think of it often. _Tenser, tenser, said the tensor_ rings in my head for no reason every now and then.

Added 'The Demolished Man'

---

readme.md

Added 'Jem'

---

readme.md

Added 'Cities in Flight'

---

readme.md

Added 'Riddley Walker'

---

readme.md

Just added my name to what I've said.

Sourced my commentaries

---

readme.md

Added 'Star Trek II: The Wrath of Khan'

---

readme.md

Added director field

---

readme.md

Moved _The Door Into Summer_ into Time Travel, too.

Added 'Behold the Man' and Time Travel section

---

readme.md

Added 'The Deep Range'

---

readme.md

See https://github.com/sindresorhus/awesome-scifi/pull/71#discussion_r30949052

Added better reason why I suggest this

---

readme.md

I have a few collections that would be good to add, but they differ in genre and style at times. I think this should be a section.

Added Short Story section

---

readme.md

Moved Star Trek into it, and also renamed TV Series from TV-series.
Discuessed in #45

Added Movie Series section

---

readme.md

I had already created an issue #79 that explains the project.
Unfortunately, I got a little bored so I've decided to go ahead and edit the file without waiting for project managers to confirm that this issue needs to be resolved.

Added the year next to the titles

---

contributing.md

Since #80 got accepted, it would be useful to correct the way contributors should add new things to the list.

Corrected the format used to add new things to the list in contribute.md

---

readme.md

Added Murakami's _Hard-Boiled_ to the novels.
As for movies, I noticed no anime on the list so far. Added the classics:
+ Akira
+ Paprika
+ NGE
+ Ghost in the shell

Add favorites from Japan

---

readme.md

https://en.wikipedia.org/wiki/Fahrenheit_451

Fahrenheit 451 was published in 1953, not 2013!

---

readme.md

I added the commentary to the movies I watched in the last couple of months: Transcendence, Her, Lucy, Ex Machina, Chappie and Interstellar.
I will not submit the patch directly to the master branch so other contributors can say their opinion about my comments. They might be a bit subjective for this list.

Added my commentary on a couple of movies

---

readme.md

Proposed addition to Short Stories.
Pull request instead of commit push since it's not a presentation or syntax change, but a content change, and I'd like people to voice their opinions :)

Add Egan's _Axiomatic_ SSC

---

readme.md

Adding 'Nexus' to hard Sci-Fi. 🔬📖

Adding 'Nexus' to hard Sci-Fi. 🔬📖

---

readme.md

Adding 'Hackers' to movies. 💾📟

Adding 'Hackers' to movies. 💾📟

---

readme.md

Added District 9

---

readme.md

> Babel-17 is all about the power of language. Humanity, which has spread throughout the universe, is involved in a war with the Invaders, who have been covertly assassinating officials and sabotaging spaceships. The only clues humanity has to go on are strange alien messages that have been intercepted in space. Poet and linguist Rydra Wong is determined to understand the language and stop the alien threat.

Added Babel-17

---

readme.md

Added cross-links to awesome-fantasy

---

readme.md

Added 'The Island of Dr. Death And Other Stories and Other Stories

---

readme.md

Not gonna merge the pull request directly so someone can proof read it and approve it if I did everything right.
I didn't follow the comments directly from the issue. I put my comment on the second place because I was referencing to the first comment when I mentioned Groundhog Day. I hope that's okay with you.

Add `Edge of Tomorrow` (2014) to the Movies section (fixed #105)

---

readme.md

Add commentary to Minority Report

---

readme.md

Change for issue #109
A fun and fast-paced hard-boiled cyberpunk noir, almost impossible to put down. - [@helderroem](https://github.com/helderroem)
> It's the twenty-fifth century, and advances in technology have redefined life itself. A person's consciousness can now be stored in the brain and downloaded into a new body [or "sleeve"], making death nothing more than a minor blip on a screen. Onetime U.N. Envoy Takeshi Kovacs has been killed before, but his last death was particularly painful. Resleeved into a body in Bay City [formerly San Francisco], Kovacs is thrown into the dark heart of a shady, far-reaching conspiracy that is vicious even by the standards of a society that treats existence as something that can be bought and sold. For Kovacs, the shell that blew a hole in his chest …

Add Altered Carbon

---

contributing.md

Proposed changes to the contribution guidelines, as per #121 .

Guidelines for linking author names as per #121

---

readme.md

Implementation of the consensus in #121 .

Linked author names as per #121

---

readme.md

Added `The Fifth Element`

---

contributing.md

Added a note about adding commentaries to the Contribute.

---

readme.md

Added `Red Dwarf`

---

readme.md

Added comment about Sunshine

---

readme.md

A first stab at this. This should close #83, but we may have to do a bit of editing afterwards.

Added categories to movies

---

readme.md

This should enable us to close #144, #142, #127, #113, #112, and #110.

Added a suggestion section

---

contributing.md

Added suggested note, removed date from PR, and added note about categories to contributing.

Small edits to Contributing

---

readme.md

Big fan of the show, and of the complete franchise. Certainly feels awesome to me. I've added a personal comment to the post as well.

Added `Stargate Universe`

---

readme.md

:+1: Can't wait for the movie. 
https://www.youtube.com/watch?v=Ue4PCI0NamI

Added a comment to `The Martian`

---

readme.md

Added my commentary to `Children of Men`

---

readme.md

Good enough to be on this list.

Added Vanilla Sky

---

readme.md

Better than vanilla sky. Very good.

Added Possible Worlds

---

readme.md

:fire: :book: :fire: :fire_engine:

Added Commentary to `Fahrenheit 451`

---

readme.md

This has been unattributed since the root commit. Added attribution. 
[Found it!](https://twitter.com/NaxYoMizmo/status/557671600200638466)

Added attribution to `The Dispossessed` comment

---

readme.md

Also removes an open bracket from the description of the invisible man.

Added Liu Cixin's Three body

---

readme.md

Added Frankenstein, arguably the first modern sci fi novel that still resonates today.
Edit: Sorry about opening so many PRs. I'm new to doing multiple PRs and I've been having some troubles trying to make two separate ones for the two separate changes. In the future I'll make sure to make my branches right away and to not make so many unnecessary PRs (I figured I could delete them, not just close them...)

Added Frankenstein, arguably the first modern sci fi novel that still resonates today.

---

readme.md

Added comment to Battlestar Galactica

---

readme.md

Added `The Island`

---

readme.md

Philip K. Dick is under represented in this list in my opinion, and this is my favourite Dick novel by far.

added The Man in the High Castle by Philip K. Dick

---

readme.md

Added `The Martian`

---

contributing.md

Added a section about updating your PR

---

readme.md

CF @sindresorhus's twitter [comment](https://twitter.com/sindresorhus/status/663467763973750784).

Added Firefly comments and category

---

readme.md

Added comment to Interstellar

---

contributing.md
readme.md

Remove the suggested category

---

contributing.md

Added note to make categories easier

---

readme.md

Added `The Left Hand of Darkness`

---

readme.md

Added `Speaker for the Dead`

---

readme.md

Added a comment to `Enders Game`

---

readme.md

I love this book. Per @RichardLitt's mention, here's my recommendation. <3

Add comment/recommendation for `Ready Player One`

---

readme.md

Added a comment to `Ready Player One`

---

readme.md

Both the books and movies have their production year mentioned but the TV series did not.
This pull request fixes that. :grin: 
The years have been taken from each respective TV serie's IMDB page or from Wikipedia for series that have made a comeback.
TV series that are still running have a start but not and end year, just as on IMDB.

📺 Adds years to television series.

---

readme.md

An amazing book about time travels by René Barjavel. Original title : "Le voyageur imprudent"

Add Future Times Three

---

readme.md

Another book from Barjavel, also known as "La nuit des temps".

Add The Ice People

---

readme.md

I didn't add a comment since in this case it's quite easy to inadvertently spoil the movie, btw it's a classic, came out the same year of the matrix but is focused on the interactions between the real world and the virtual, no slow motion gun fights here :)

Added The Thirteenth Floor to Movies

---

readme.md

Great series and an amazing book, they need at least one enthusiastic comment.

Added comment to SG1 and Permutation City

---

readme.md

This list is 5 years old, but it's a great look into the classics that make up modern sci-fi and fantasy taken from the perspectives of NPR listeners.

Adding new link

---

readme.md

I've switched the images of emoji to be emoji characters themselves. The main benefit of doing this is that it is now possible to search the document for them when viewing in a browser.

Switch images to emoji

---

readme.md

A beautiful film, weaving together memory, languages, and the other. The film is less about aliens and more about our perception of them; like District 9, this film functions as a good mirror for how different people and governments deal with alien interaction. The music is also exceptional.

Add `Arrival`

---

readme.md

Alex + Ada is a thought provoking and moving exploration of what it means to be alive, and what rights can and should be afforded to non-human sentient beings. It's a short and effective near-future look at the obligations we have to both each other and to the intelligent life we create.

Add `Alex + Ada` to Comic Books section

---

readme.md

Adds Never Let Me Go by Kazuo Ishiguro.
Also my text editor automatically removes superfluous whitespace, which explains the other small formatting changes.

Add Never Let Me Go

---

readme.md

Alphabetize Comic books section of list.

---

readme.md

See https://github.com/sindresorhus/awesome-scifi/issues/225

Adding my review of _Ender's Game_

---

readme.md

As part of https://github.com/sindresorhus/awesome-scifi/issues/226

Add Borne review

---

readme.md

added some personal comments to 2 books.

added commentary to The Diamond Age and Oryx and Crake

---

readme.md

I found it really shocking that this movie wasn't already here.

Add Contact (1997)

---

readme.md

I had previously added the Comic Book category as well as some suggestions, but I forgot to add their respective ratings at GoodReads. This PR fixes this :)

Add Ratings to Comic Book suggestions

---

readme.md

Hello, I'ved added an entry to the sci-fi movies list.

Add Dark City (1998)

---

readme.md

This book series is a major part of the reason I am glad to be subscribed to kindle unlimited.

add Bobiverse series

---

readme.md

While Discovery is fundamentally quite different from much of the Trek that's come before, its engagement with the franchise, and willingness to both celebrate and examine its core values, keep it true to that spirit. As the medium of television evolves, it's comforting to know that Star Trek is there to evolve right along with it.

Add Star Trek: Discovery

---

readme.md

Hyperion has more than 140 000 ratings on Goodreads

Add flames to the Hyperion

---

readme.md

Person of Interest being my favorite sci-fi show, I simply had to recommend it.

Add Person of Interest to TV Shows

---

readme.md

These could just as easily fit under the Fantasy heading here, too.

Add Magic 2.0 series by Scott Meyer

---

readme.md

Sorry this took so long. I had forgotten about this

Issue #244 Fixed an error in a link and added some more movies

---

readme.md

Rick and Morty is an awesome sci-fi show that I thought should definitely make it to this list. What do you think?

Added Rick and Morty to list of TV shows

---

readme.md

I've added Neal Asher's *Polity* series to the Science Fiction section, as well as adding Vernor Vinge's _A Deepness in the Sky_ to the hard sci-fi section.  I feel like my description of the *Polity* series is a bit long, but the series includes almost 20 books, including three distinct sub-series and several standalone novels.
As for my bonafides, I'm 37 and have been a voracious reader (1-3 books a week) since I was in elementary school... and over half of those books have been science fiction.  I saw many of my favorite books and series already in the list, but the novel and series that I added were, IMHO, glaring omissions.

Added Neal Asher's Polity series, & Vinge's A Deepness in the Sky

---

readme.md

This is a rare case where the movie is a as good as the book. One of the last projects from the great Carl Sagan, this is a must read for any sci-fi fan, or amateur cosmologist.

Added Contact by Carl Sagan

---

readme.md

Funny, touching, and full of unexpected details. - [@lgierth](https://github.com/lgierth)
> Follow a motley crew on an exciting journey through space—and one adventurous young explorer who discovers the meaning of family in the far reaches of the universe—in this light-hearted debut space opera from a rising sci-fi star.
>
> Life aboard the Wayfarer is chaotic and crazy—exactly what Rosemary wants. It’s also about to get extremely dangerous when the crew is offered the job of a lifetime. Tunneling wormholes through space to a distant planet is definitely lucrative and will keep them comfortable for years. But risking her life wasn’t part of the plan. In the far reaches of deep space, the tiny Wayfarer crew will confront a host of unexpected mishaps and thrilling adventures that force them …

Add The Long Way to a Small, Angry Planet

---

readme.md

A smart script and-ahead-of their-time effects elevate this one from a cult classic to a landmark of the Sci-Fi genre.

Add Forbidden Planet

---

readme.md

I can't say I've ever been "excited" to read a book, but after hearing about _House of Leaves_ I was undeniably excited. I was in the middle of another book when my wife surprised me with this one, and I finished the book I was already reading much more quickly than I normally would have just so I could start reading _House of Leaves_.
If you're looking for a book which lays out all the answers for you and packages things up neatly with a bow, this is not for you 😄
---
This book is widely considered "horror" as well but I wasn't sure if a new "Horror" subsection should be created, so I put the entry in the general "Science Fiction" section. If you'd like a "Horror" subsection created as part of this PR, let me know and I can add it and move _House of Leaves_ there!

Add House of Leaves

---

readme.md

This PR adds `Eureka` TV Series - enjoyed it very much.
P.S. My editor automatically removed trailing line spaces and I've noticed this quite late. Please let me know if I should revert it back.

Add 'Eureka' TV Series

---

readme.md

Added the sequel to Blade Runner

Added Blade Runner 2049 to Movies

---

readme.md

- Add The Songs of Distant Earth by Arthur C. Clarke

Add The Songs of Distant Earth by Arthur C. Clarke

---

readme.md

This book gets pretty crazy and deep, and really makes you think "What makes me me?" I can't really say much more than what is in the description without spoiling everything!

Add Dark Matter by Blake Crouch

---

readme.md

First of a two part series.  Took the first section of the goodreads description for the sake of brevity.  It's several paragraphs long.

Adding Pandemic by A.G. Riddle

---

readme.md

I think the Red Dwarf books are the best books I ever read and should be listed in any list of science fiction books.

Add the books about Red Dwarf by Grant Naylor

---

readme.md

Also snuck a tiny typo fix in there.

Added Neal Stephensons "REAMDE"

---

readme.md

As requested per https://twitter.com/richlitt/status/1260374897743798273
(Both lists have been created by @Potherca)

Add links to lists on Letterboxd and Goodreads.

---

readme.md

For increased security, it is [advised to prefer HTTPS](https://web.dev/why-https-matters/) connections.
This changes all non-https links to https.

Replace all instances of HTTP with HTTPS

---

readme.md

Hello! I'm just alphabetizing the whole list. Let me know if something's wrong. Thanks!

Rearranged all titles in alphabetical order

---

readme.md

1966 dystopian masterpiece set to 1999

Make Room! Make Room!

---

readme.md

Added this great collection of short stories.

Cory Doctorows "Radicalized"

---

readme.md

Add last 9th book to the serie `Expanse`

---

readme.md

Added Aurora Cycle series to Military section

Added Aurora Cycle series

---

contributing.md
readme.md

Spoiler tags
- Reformatted every description to follow the new spoiler tag format
- Changed the contributing readme to reflect this standard
Cleanup
- The Xenogenesis books were out of their elements, put them under Xenogenesis entry
- Some typos (missing period, wrong formats etc).
Additions
- Becky Chambers "A psalm for the wild-built"
- Adrian Tchaikovsky "Children of time"
https://github.com/sindresorhus/awesome-scifi/issues/310

Spoiler tags

---

readme.md

I think the original foundation trilogy deserves a spot on this list, rather than just book one. The trilogy is foundational (haha) to the genre and critically acclaimed. I used the Expanse series as a guide for the formatting of a book series.
I wondered if the entire series (7 books) should be included, rather than just the original trilogy? My personal take is that the original trilogy is the awesome one, but I'm sure you could argue the entire series deserves a spot!

Update the foundation entry to include the original trilogy

---

readme.md

A delightful gem I happened to come across that combines lighthearted adventure with heartwarming moments and a touch of retro-futurism.

added The Rolling Stones by Russell Ho

---

readme.md

Hello there,
I've added the movie Tenet by Christopher Nolan (2020) to the README file.
Comments, links, and the description should be aligned with your preferences.
Greetings.

add movie Tenet (2020)
